apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: frontend
    environment: dev
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80