apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
    - name: sidecar
      image: busybox:latest
      command: ["sh", "-c", "while true; do echo 'Sidecar running'; sleep 10; done"]