apiVersion: v1
kind: Pod
metadata:
  name: config-demo-pod
spec:
  containers:
    - name: demo-container
      image: nginx:latest
      env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: demo-config
              key: DATABASE_URL